version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend/api/requirements.txt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/backend/gateway/requirements.txt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/package-lock.json"
    schedule:
      interval: "weekly"
