version: '3.8'
# this is the version of docker-compose that is used for benchmarking
services:
  orion:
    image: fiware/orion:3.8.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo-db
    healthcheck:
      test: curl --fail -s http://localhost:1026/version || exit 1
      interval: 30s
      timeout: 30s
      retries: 3

  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: fiware-mongo-db
    expose:
      - "27017"
    networks:
      - default
    ports:
      - "27017:27017"
    command: --nojournal
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:15.2
    hostname: postgres
    container_name: fiware-postgres
    expose:
      - "5432"
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=iot_devices
      - POSTGRES_USER=karelia
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U orion -d orion -h localhost
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:7.1
    hostname: pgadmin
    container_name: fiware-pgadmin
    expose:
      - "80"
    networks:
      - default
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=karelia@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    depends_on:
      - postgres
    healthcheck:
      test: curl --fail -s http://localhost:8080 || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
  
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    hostname: mosquitto
    container_name: fiware-mosquitto
    expose:
      - "1883"
    networks:
      - default
    ports:
      - "1883:1883"
    healthcheck:
      test: mosquitto_sub -h localhost -t test -C 1
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /home/temavasilev/.config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  quantumleap:
    image: smartsdk/quantumleap:0.8.0
    hostname: quantumleap
    container_name: fiware-quantumleap
    expose:
      - "8668"
    networks:
      - default
    ports:
      - "8668:8668"
    depends_on:
      - orion
      - crate
    healthcheck:
      test: curl --fail -s http://localhost:8668/version || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - CRATE_HOST=crate
  
  crate:
    image: crate:4.6.8
    hostname: crate
    container_name: fiware-crate
    expose:
      - "4200"
    networks:
      - default
    ports:
      - "4200:4200"
    healthcheck:
      test: curl --fail -s http://localhost:4200 || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - CRATE_HEAP_SIZE=2g
      - TZ=Europe/Berlin
    volumes:
      - crate:/data

networks:
  default:
    name: fiware
    driver: bridge

volumes:
  crate: