version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - bachelor_project
    volumes:
      - ./frontend:/dist  # for hot reloading
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - bachelor_project
    volumes:
      - ./backend:/app  # for hot reloading
    environment:
      - ORION_URL=http://orion:1026
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=karelia
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=iot_devices
      - FIWARE_SERVICE=mqtt_gateway
      - FIWARE_SERVICEPATH=/mqttgateway
      - API_KEY=plugnplay

networks:
  bachelor_project:
    external: true