version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mqtt_gateway_frontend
    ports:
      - 5173:5173
    networks:
      - bachelor_project
    volumes:
      - ./frontend:/dist  # for hot reloading
    
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: mqtt_gateway_api
    ports:
      - 8000:8000  
    networks:
      - bachelor_project
    volumes:
      - ./backend/api:/app  # for hot reloading
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    networks:
      - bachelor_project
    volumes:
      - ./backend/gateway:/app  # for hot reloading
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  bachelor_project:
    external: true
