name: Code Scanning Alert Issue Creator

on:
  code_scanning_alert:
    types: [created, reopened]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create issue for new code scanning alert
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const alert = context.payload.alert;
            const rule = alert.rule;
            const issueTitle = `Code Scanning Alert: ${rule.description}`;
            const issueBody = `
              **Severity:** ${alert.rule.security_severity_level}\n
              **Description:** ${alert.most_recent_instance.message}\n
              **Tool:** ${alert.tool.name}\n
              **Affected File:** ${alert.most_recent_instance.location.path}\n
              **More Info:** [${alert.html_url}](${alert.html_url})\n
              
              A new code scanning alert has been detected. Please review and take necessary actions.
            `;

            // Check if an issue already exists with the same title
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const issueExists = issues.data.some(issue => issue.title === issueTitle);

            if (!issueExists) {
              const { data: issue } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody
              });

              console.log(`Issue created: ${issue.html_url}`);
            } else {
              console.log(`Issue already exists: ${issueTitle}`);
            }
