name: Create Issues from Dependabot Alerts

on:
  push:
    branches:
      - 30-setup-dependabot-workflow

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Dependabot alerts
        id: fetch_alerts
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEPENDABOT_PAT }}
          script: |
            const alerts = await github.request('GET /repos/{owner}/{repo}/dependabot/alerts', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            if (!alerts.data || alerts.data.length === 0) {
              core.notice('No Dependabot alerts found.');
              return;
            }

            return JSON.stringify(alerts.data.map(alert => ({
              number: alert.number,
              package_name: alert.security_advisory.identifier,
              severity: alert.security_advisory.severity,
              summary: alert.security_advisory.summary,
              url: alert.html_url
            })));

      - name: Create issues
        if: ${{ steps.fetch_alerts.outputs.result != 'null' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEPENDABOT_PAT }}
          script: |
            const alerts = JSON.parse('${{ steps.fetch_alerts.outputs.result }}');
            if (!alerts || alerts.length === 0) {
              console.log('No alerts to create issues for.');
              return;
            }

            for (const alert of alerts) {
              const issueTitle = `Security Alert: ${alert.package_name} - ${alert.severity}`;
              const issueBody = `
                A security vulnerability has been detected in the \`${alert.package_name}\` package.

                **Severity**: ${alert.severity}

                **Summary**: ${alert.summary}

                **Details**: [View alert](${alert.url})

                Please review and address this issue accordingly.
              `;

              console.log('Creating issue with title:', issueTitle);
              console.log('Creating issue with body:', issueBody);

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: issueBody
              });
            }
