name: setup-docker-and-run-tests.yml

on: [push]

jobs:
  setup-and-start-services:
    name: Setup Docker and Start Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fiware Environment
        run: | 
          cd fiware-environment
          docker compose pull
          docker compose up -d

      - name: Build docker images
        run: |
          cd n5geh.tools.mqtt-gateway/
          docker compose build
          docker compose up -d

      - name: Wait for service to be ready
        run: |
          until curl -s http://localhost:5173; do
            echo "Waiting for service to be ready..."
            sleep 5
          done

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup-and-start-services

    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Run tests
        run: |
          cd tests
          python -m unittest test_crud.py