name: Snyk Container Scan and Create Issues

on:
  push:
    branches:
      - 20-security-scan-of-the-image
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build API image
      run: docker build -t n5gehtoolsmqtt-gateway-api:latest -f ./backend/api/Dockerfile .

    - name: Build Gateway image
      run: docker build -t n5gehtoolsmqtt-gateway-gateway:latest -f ./backend/gateway/Dockerfile .

    - name: Snyk Scan API image
      id: snyk_api_scan
      uses: snyk/actions/docker@master
      with:
        image: 'n5gehtoolsmqtt-gateway-api:latest'
        args: '--severity-threshold=high --json-file-output=snyk_api_results.json'
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Snyk Scan Gateway image
      id: snyk_gateway_scan
      uses: snyk/actions/docker@master
      with:
        image: 'n5gehtoolsmqtt-gateway-gateway:latest'
        args: '--severity-threshold=high --json-file-output=snyk_gateway_results.json'
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Upload Snyk API scan results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-api-results
        path: snyk_api_results.json

    - name: Upload Snyk Gateway scan results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: snyk-gateway-results
        path: snyk_gateway_results.json

    - name: Create issues from Snyk API scan
      if: always()
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const snykResults = JSON.parse(fs.readFileSync('snyk_api_results.json', 'utf-8'));
          
          const highCriticalVulnerabilities = snykResults.vulnerabilities.filter(vuln => 
            vuln.severity === 'high' || vuln.severity === 'critical'
          );

          for (const vuln of highCriticalVulnerabilities) {
            const issueTitle = `Snyk Security Alert: ${vuln.title} - ${vuln.severity}`;
            const issueBody = `
              A security vulnerability has been detected in the \`${vuln.packageName}\` package.

              **Severity**: ${vuln.severity}

              **Summary**: ${vuln.title}

              **Description**: ${vuln.description}

              **Details**: [View alert](${vuln.url})

              Please review and address this issue accordingly.
            `;

            console.log('Creating issue with title:', issueTitle);
            console.log('Creating issue with body:', issueBody);

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });

            // Add a delay to avoid rate limit issues
            await new Promise(resolve => setTimeout(resolve, 2000));
          }

    - name: Create issues from Snyk Gateway scan
      if: always()
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const snykResults = JSON.parse(fs.readFileSync('snyk_gateway_results.json', 'utf-8'));
          
          const highCriticalVulnerabilities = snykResults.vulnerabilities.filter(vuln => 
            vuln.severity === 'high' || vuln.severity === 'critical'
          );

          for (const vuln of highCriticalVulnerabilities) {
            const issueTitle = `Snyk Security Alert: ${vuln.title} - ${vuln.severity}`;
            const issueBody = `
              A security vulnerability has been detected in the \`${vuln.packageName}\` package.

              **Severity**: ${vuln.severity}

              **Summary**: ${vuln.title}

              **Description**: ${vuln.description}

              **Details**: [View alert](${vuln.url})

              Please review and address this issue accordingly.
            `;

            console.log('Creating issue with title:', issueTitle);
            console.log('Creating issue with body:', issueBody);

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });

            // Add a delay to avoid rate limit issues
            await new Promise(resolve => setTimeout(resolve, 2000));
