name: Snyk Scan Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build API Docker image
      run: docker build -t n5gehtoolsmqtt-gateway-api:latest -f ./backend/api/Dockerfile .

    - name: Build Gateway Docker image
      run: docker build -t n5gehtoolsmqtt-gateway-gateway:latest -f ./backend/gateway/Dockerfile .

    - name: Snyk Scan API image
      id: snyk-api
      uses: snyk/actions/docker@master
      with:
        image: n5gehtoolsmqtt-gateway-api:latest
        args: --severity-threshold=high

    - name: Snyk Scan Gateway image
      id: snyk-gateway
      uses: snyk/actions/docker@master
      with:
        image: n5gehtoolsmqtt-gateway-gateway:latest
        args: --severity-threshold=high

    - name: Parse and create GitHub issues for API image vulnerabilities
      if: ${{ steps.snyk-api.outputs.vulnerabilities }}
      run: |
        echo "Parsing Snyk API scan results..."
        severity=""
        description=""
        info=""
        echo "${{ steps.snyk-api.outputs.vulnerabilities }}" | while read -r line; do
          if [[ $line == *"severity"* ]]; then
            severity=$(echo $line | awk '{print $3}')
          elif [[ $line == *"Description"* ]]; then
            description=$(echo $line | awk '{print $2}')
          elif [[ $line == *"Info"* ]]; then
            info=$(echo $line | awk '{print $2}')
            gh issue create --title "$severity vulnerability found in API image" --body "Description: $description\nInfo: $info"
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Parse and create GitHub issues for Gateway image vulnerabilities
      if: ${{ steps.snyk-gateway.outputs.vulnerabilities }}
      run: |
        echo "Parsing Snyk Gateway scan results..."
        severity=""
        description=""
        info=""
        echo "${{ steps.snyk-gateway.outputs.vulnerabilities }}" | while read -r line; do
          if [[ $line == *"severity"* ]]; then
            severity=$(echo $line | awk '{print $3}')
          elif [[ $line == *"Description"* ]]; then
            description=$(echo $line | awk '{print $2}')
          elif [[ $line == *"Info"* ]]; then
            info=$(echo $line | awk '{print $2}')
            gh issue create --title "$severity vulnerability found in Gateway image" --body "Description: $description\nInfo: $info"
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
