name: Snyk Docker Scan

on:
  push:
    branches:
      - 20-security-scan-of-the-image
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build API image
      run: docker build -t n5gehtoolsmqtt-gateway-api:latest -f ./backend/api/Dockerfile .

    - name: Build Gateway image
      run: docker build -t n5gehtoolsmqtt-gateway-gateway:latest -f ./backend/gateway/Dockerfile .

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk to check API Docker image for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk container test n5gehtoolsmqtt-gateway-api:latest --json > snyk-api-report.json

    - name: Run Snyk to check Gateway Docker image for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk container test n5gehtoolsmqtt-gateway-gateway:latest --json > snyk-gateway-report.json

    - name: Filter high and critical vulnerabilities for API image
      run: |
        jq '.vulnerabilities |= map(select(.severity == "high" or .severity == "critical"))' snyk-api-report.json > snyk-api-high-critical-report.json
      shell: bash

    - name: Filter high and critical vulnerabilities for Gateway image
      run: |
        jq '.vulnerabilities |= map(select(.severity == "high" or .severity == "critical"))' snyk-gateway-report.json > snyk-gateway-high-critical-report.json
      shell: bash

    - name: Check if API report contains high or critical vulnerabilities
      id: api_vuln_check
      run: |
        count=$(jq '.vulnerabilities | length' snyk-api-high-critical-report.json)
        echo "::set-output name=has_vulnerabilities::$count"

    - name: Check if Gateway report contains high or critical vulnerabilities
      id: gateway_vuln_check
      run: |
        count=$(jq '.vulnerabilities | length' snyk-gateway-high-critical-report.json)
        echo "::set-output name=has_vulnerabilities::$count"

    - name: Create GitHub issues for API image vulnerabilities
      if: steps.api_vuln_check.outputs.has_vulnerabilities > 0
      uses: JasonEtco/create-an-issue@v2
      with:
        filename: snyk-api-high-critical-report.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub issues for Gateway image vulnerabilities
      if: steps.gateway_vuln_check.outputs.has_vulnerabilities > 0
      uses: JasonEtco/create-an-issue@v2
      with:
        filename: snyk-gateway-high-critical-report.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
